[Implements #9] Default to using ffmpeg for audio and screenshots, fallback to mpv if ffmpeg fails
migaku-official/migaku-mpv pull request #11
Opened 2021-12-26 04:41 UTC by christofferaakre

Not sure if you guys accept pull requests, but I had a go at implementing #9. Sorry for the messy diff. Let me know if there is anything I should change before you can merge this!

2022-01-04 15:01 UTC, RicBent commented
Hey there! Thanks for the contribution.

Actually this was already somewhat implemented in https://github.com/migaku-official/migaku-mpv/tree/ffmpeg-export

The main reason this was not yet merged is that migaku mpv actually allows creating cards from web resources like YouTube and Viki. Switching to ffmpeg breaks that use case. What might work however is first attempting to export the media with ffmpeg and then use mpv as a fallback on failure.

2022-01-04 15:57 UTC, christofferaakre commented
> Hey there! Thanks for the contribution.
> 
> Actually this was already somewhat implemented in https://github.com/migaku-official/migaku-mpv/tree/ffmpeg-export
> 
> The main reason this was not yet merged is that migaku mpv actually allows creating cards from web resources like YouTube and Viki. Switching to ffmpeg breaks that use case. What might work however is first attempting to export the media with ffmpeg and then use mpv as a fallback on failure.

I see. The code I wrote does actually fallback to mpv if ffmpeg fails

2022-01-06 21:06 UTC, RicBent commented
Oh I'm actually blind. Sorry for that.

Will check it out and merge it asap.

2022-01-06 21:11 UTC, RicBent requested changes
This looks fine!

Just this thing needs to be fixed before I'll merge it. Especially Windows users wouldn't have `ffmpeg` in `PATH`.

2022-01-06 21:11 UTC, RicBent commented on utils/ankiexport.py
> +                'ffmpeg',
This should use the ffmpeg executable from https://github.com/migaku-official/migaku-mpv/blob/063fe424754af72350d2ad6935c5bd57d35a1d3d/migaku_mpv.py#L783

2022-01-06 21:11 UTC, RicBent commented on utils/ankiexport.py
> +                'ffmpeg',
This should use the ffmpeg executable from https://github.com/migaku-official/migaku-mpv/blob/063fe424754af72350d2ad6935c5bd57d35a1d3d/migaku_mpv.py#L783

2022-01-06 21:54 UTC, christofferaakre commented
@RicBent just doing `from migaku_mpv import find_executable` in `ankiexport.py` doesn't work since they are not in the same directory, and I don't really want to mess with the directory strucutre. I see there is an `__init__.py` file in `utils`, but I am not quite sure what the package structure is supposed to be like.

2022-01-06 23:51 UTC, RicBent commented
The best solution probably would be handling it the same way as `mpv_executable` as that file was meant as something independent that could be reused in other projects later down the line. References for how `mpv_executable` is set:

https://github.com/migaku-official/migaku-mpv/blob/063fe424754af72350d2ad6935c5bd57d35a1d3d/migaku_mpv.py#L490
https://github.com/migaku-official/migaku-mpv/blob/063fe424754af72350d2ad6935c5bd57d35a1d3d/utils/ankiexport.py#L12

2022-01-08 09:21 UTC, RicBent commented
Thanks a lot! Merging~

2022-01-08 09:21 UTC, merged

2022-01-08 09:23 UTC, christofferaakre commented
Great! Thanks for being patient with me